return {

    Coin = {
        Cash = 10000,
        Gems = 0,
        Crystals = 0,
        CashMultiplier = 1,
        VipMultiplier = 1
    },

    Tower = {
        Inv = {
            
        },
        Collection = {
            Total = 0
        },
        Clone = {
            SourceUID = false,
            EndTime = 0,
            SourceUID2 = false,
            EndTime2 = 0,
        },
        Evolve = {
            SourceUID = false,
            EndTime = 0,
        },
    },
    Totem = {
        Inv = {},
        Equipped = false,
        Equipped2 = false,
        Equipped3 = false,
        Slot2Unlocked = false,
    },

    Item = {
        Inv = {
        },
    },

    PVP = {
        Shop = {
            Day = 0,
            Count = {},
        },
        Challenge = {
            Count = 7,
            RecoverTime = 0,
        },
    },

    Grid = {
        Width = 4,
        Height = 4,
        Skins = {
            [1] = true, [2] = false, [3] = false, [4] = false, [5] = false,
        },
        CurSkin = 1,
    },

    Gacha = {
        Luck = 1,
        LegendaryPity = 0,
        MythicPity = 0,
        SecretPity = 0,
        LastSpin = 0,
        Spins = 1,
        PlayTime = 0
    },

    VIP = {
        ['VIP'] = false,
        ['DoubleCash'] = false,
        ['DoubleLuck'] = false,
        ['TripleLuck'] = false,
        ['StarterPack'] = false,
        ['Dropx2'] = false,
        ['Mutationx2'] = false,
        ['FastRoll'] = false,
        ['AutoMerge'] = false,
        ['TotemSlot'] = false,
        ['CloneSlot'] = false,
    },

    States = {
        Aura = 0,
        GroupReward = false,
        VIPDaily = 0,
        PlaceVersion = 0,
        OfflineReward = {Items = {}, Cash = 0, },
        IsNew = true,
        PVPDeploy = {},
        LoginReward = {
            Day = 1,
            LastLoginDay = 0,
        },
        WeeklyDaily = {
            Day = 1,
            LastLoginDay = 0,
        },
    },

    Profile = {
        BossKills = 0,
        Kills = 0,
        MaxLevel = 1,
        MaxChallenge = 1,
        StartLevel = 1,
        CardLevel = 1,
        Spend = 0,
        CrystalsTotal = 0,
    },

    Guide = {
       [1] = false,
       [2] = false,
       [3] = false,
       [4] = false,
       [5] = false,
    },

    BossChallenge = {
        Count = 3,
        RecoverTime = 0,
    },

    Task = {
        Claimed = {
            [1] = false, [2] = false, [3] = false, [4] = false, [5] = false, [6] = false, [7] = false, [8] = false, [9] = false, [10] = false, 
            [11] = false, [12] = false, [13] = false, [14] = false, [15] = false, [16] = false, [17] = false, [18] = false, [19] = false, [20] = false, 
            [21] = false, [22] = false, [23] = false, [24] = false, [25] = false, [26] = false, [27] = false, [28] = false, [29] = false, 
        },
        Claimed1 = {
            [1] = false, [2] = false, [3] = false, [4] = false, [5] = false, [6] = false, [7] = false, [8] = false, [9] = false, [10] = false,
            [11] = false, [12] = false, [13] = false, [14] = false, [15] = false, [16] = false, [17] = false, [18] = false, [19] = false,
        },
        Claimed2 = {
            [1] = false, [2] = false, [3] = false, [4] = false, [5] = false, [6] = false, [7] = false, [8] = false, [9] = false, [10] = false, 
            [11] = false, [12] = false, [13] = false, [14] = false, [15] = false, [16] = false, [17] = false, [18] = false, [19] = false, [20] = false, [21] = false, [22] = false, 
        },
    },

    Analytics = {
        

    },

}